server:
  port : 1111

spring:
  application:
    name: apigateway_microservice
    cloud :
        gateway :
          routes :
            - id : Student
              uri : lb://Student
              predicates :
                - Path =/student/**
            - id : demo_microservice
              uri : lb://demo_microservice
              predicates :
                - Path =/departments/**

  eureka:
    client :
      register-with-eureka :
        fetch-registry :
          service-url :
            defaultZone: http://localhost:8761/eureka/
          instance :
hostname: localhost





